version: 3.9
services:
  app:
    container_name: app_bot
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./share:/usr/app/share
    restart: unless-stopped
    links:
      - redis
  redis:
    container_name: redis_bot
    image: redis:alpine
    restart: always