version: 3.9
services:
  node:
    container_name: bot
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./share:/usr/app/share
    restart: unless-stopped
    links:
      - redis
  redis:
    container_name: redis
    image: redis:alpine
    restart: always